### ISSUE TITLE
Web Browser MIA - Running Workspace on Windows 11

### ISSUE THREAD

**Issue by NaokaSky** [ODU-CGA-CubeSat/sealion-workspace-image#18]
Image ID: 486c682aefa0

![Screenshot (102)](https://user-images.githubusercontent.com/120331217/214401445-d91e5fb4-a0d9-402b-a2f1-2eb0ecde79f4.png)

**Comment by capsulecorplab** [comment]
closed as per https://github.com/ODU-CGA-CubeSat/sealion-workspace-image/issues/32#issuecomment-1622619927
