### ISSUE TITLE
Unable to Git Clone inside kasm workspace using ssh (running on WSL host machine), despite ssh keys configured with github

### ISSUE THREAD

**Issue by kchiu002** [ODU-CGA-CubeSat/sealion-workspace-image#33]
Attempting to use git clone prompts the following text.

```
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Unable to git clone.

**Comment by kchiu002** [comment]
`ping google.com` returns 
`ping: google.com: Temporary failure in name resolution`

**Comment by capsulecorplab** [comment]
This looks relevant https://stackoverflow.com/questions/20430371/my-docker-container-has-no-internet

**Comment by kchiu002** [comment]
Starting the daemon with `sudo dockerd --iptables=true` will fix the issue.
