### ISSUE TITLE
Eclipse IDockerConnection Error

### ISSUE THREAD

**Issue by juman004** [ODU-CGA-CubeSat/sealion-workspace-image#4]
![EclipseError](https://user-images.githubusercontent.com/91851880/174163672-02387a5d-189d-4c12-88e6-573fce0c8152.PNG)

Error isn't always present, tends to pop up at random times. However, when the it does pop up eclipse basically become useless since it wont let you right click anywhere within eclipse. My current workaround as been to delete the .metafile in the workspace and reimport the projects. This is only a temporary fix, resulting in the error returning after some time.  
[logfile.txt](https://github.com/ODU-CGA-CubeSat/kasm-sealion-workspace/files/8922410/logfile.txt)

**Comment by capsulecorplab** [comment]
closing, as eclipse has since been removed
