### ISSUE TITLE
Kasm container can't open VS Code running on WSL

### ISSUE THREAD

**Issue by G5STER** [ODU-CGA-CubeSat/sealion-workspace-image#7]
![image](https://user-images.githubusercontent.com/99848970/188682779-faf91b95-d237-41ef-9ea7-a63f4142b2b5.png)

**Comment by G5STER** [comment]
Solution:

1) As described in terminal message, install VS Code on local machine (through Microsoft store) and remove Linux version (if it exists).

2) Install VS Code extension "Remote - WSL"

3) In settings>Extensions>Remote - WSL, set Remote.WSL2: Connection Method to localhost
![image](https://user-images.githubusercontent.com/99848970/188746833-a195bcaf-308a-43fa-ae11-e85a9a486f44.png)

4) Now running code . in wsl terminal should work

**Comment by capsulecorplab** [comment]
Closing as per https://github.com/ODU-CGA-CubeSat/sealion-workspace-image/issues/7#issuecomment-1238691502
